api/urls.py
from tastypie.api import Api
from api.models import CategoryResource, CourseResource

from django.urls import path, include

api = Api(api_name="v1")
api.register(CategoryResource())
api.register(CourseResource())

urlpatterns = [
    path('', include(api.urls), name='index')
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import CategoryResource, CourseResource


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('api/', include("api.urls")),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:course_id>', views.single_course, name='single_course')
]

api/models.py
from tastypie.resources import ModelResource
from tastypie.authorization import Authorization

from shop.models import Category, Course
from .authentication import CastomAuthentication


class CategoryResource(ModelResource):
    class Meta:
        queryset = Category.objects.all()
        resource_name = 'categories'
        allowed_methods = ['get']


class CourseResource(ModelResource):
    class Meta:
        queryset = Course.objects.all()
        resource_name = 'courses'
        allowed_methods = ['get', 'post', 'put', 'delete']
        excludes = ['created_at', 'reviews_qty']
        authentication = CastomAuthentication()
        authorization = Authorization()

    def hydrate(self, bundle):
        bundle.obj.category_id = bundle.data['category_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['category_id'] = bundle.obj.category_id
        bundle.data['category'] = bundle.obj.category
        return bundle

shop/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Course(models.Model):
    title = models.CharField(max_length=300)
    price = models.FloatField()
    students_qty = models.IntegerField()
    reviews_qty = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

api/views.py
from django.shortcuts import render

# Create your views here.

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Category, Course


def index(requests):
    courses = Course.objects.all()
    categories = Category.objects.all()
    return render(request=requests, template_name='shop/courses.html', context={'courses': courses})


def single_course(requests, course_id):
    # OPTION 1
    #    try:
    #        course = Course.objects.get(pk=course_id)
    #        return render(request=requests, template_name='single_course.html', context={'course': course})
    #    except Course.DoesNotExist:
    #        raise Http404()
    # OPTION 2
    course = get_object_or_404(Course, pk=course_id)
    return render(request=requests, template_name='shop/single_course.html', context={'course': course})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <style>
        body {
            color: black;
            background-color:rgb(71, 76, 88);
        }
        .mt-10 {
            margin-top: 100px;
        }

    </style>
</head>
<body>
    <nav class="navbar bg-dark fixed-top bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url "shop:index"%}">Courses Shop</a>
          <span class="navbar-text">
            <a href="/admin/" class="me-5" target="_blank">Admin</a>
            <a href="/api/v1/" class="me-2" target="_blank">API</a>
        </span>
        </div>
      </nav>
 
    <main class="container" style="padding-top: 48px;">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/shop/courses.html
{% extends "base.html" %}
{% block title %} All Courses {% endblock %}
{% block content%}
<table class="table mt-10 table-bordered table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Title</th>
            <th>Category</th>
            <th>Price</th>
            <th>Students_qty</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for cource in courses %}
        <tr>
            <td><a href="{% url "shop:single_course" cource.id %}">
                {{ cource.title }}
            </a></td>
            <td>{{ cource.category }}</td>
            <td>{{ cource.price }} $</td>
            <td>{{ cource.students_qty }}</td>
            <td class="text-center"><button type="button" class="btn btn-success">Buy</button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/shop/single_course.html
{% extends "base.html" %}
{% block title %}{{ course.title }}{% endblock %}
{% block content %}
<div class="card mt-5" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title"><u>{{ course.title }}</u></h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{course.category }}</h6>
        <p class="card-text">
            Students Quantity: {{course.students_qty}} <br>
            Price : {{course.price}}</p>
        <a href="#" class="card-link"><button class="btn btn-success">Buy</button></a>
        <a href="#" class="card-link"> reviews: {{course.reviews_qty}} </a>
    </div>
</div>
{% endblock %}